### ISSUE TITLE
Does not work with Borderlands 2

### ISSUE THREAD

**Issue by lilshrumpmerp** [guilhermearaujo/xboxonecontrollerenabler#10]
Just FYI. I know early on it only supported the wired Xbox 360 controller with no third party drivers, but the later updates added support for the tattiebogle driver. Not sure if using that driver as a reference helps you at all but just thought I'd throw it out there.

**Comment by guilhermearaujo** [comment]
XONE controller is different from X360, they won't work with the same drivers. I cannot guarantee full native compatibility, but you may use a key mapper to play games that don't recognize the controller.
