### ISSUE TITLE
Issue with Steam on Yosemite 10.10.1

### ISSUE THREAD

**Issue by jonochang** [guilhermearaujo/xboxonecontrollerenabler#13]
Hi Guilherme,

I've been able to get the XBox One Controller Enabler to work on Yosemite. It appears to connect and responds to buttons on the controller as per the screenshot below:

![screen shot 2015-01-05 at 12 31 30 pm](https://cloud.githubusercontent.com/assets/13179/5619438/d53f9bf8-94d6-11e4-96ec-72c6bfe8a275.png)

However, when I enter Steam as per your youtube tutorial, it doesn't appear to register the controller. Is there something else I need to do?

Thanks,

Jonathan

**Comment by guilhermearaujo** [comment]
`kext-dev-mode` should be enabled on Yosemite for improved compatibility. Instructions will be added to the readme file.
