### ISSUE TITLE
You can’t open Xone Controller preferences because it doesn’t work on an Intel-based Mac.

### ISSUE THREAD

**Issue by CSharkey145** [guilhermearaujo/xboxonecontrollerenabler#18]
I am getting this error message when I try to open Xone Controller in system preferences.

Any idea what I can do to get around this?

**Comment by guilhermearaujo** [comment]
What do you mean by "open in system preferences"?

**Comment by CSharkey145** [comment]
Click the apple button > system preferences > the Xone Controller icon is there to run, just like the instructions said.


But actually, my problem was that I was running on a very old (10.7.5) OS, I have since updated to 10.3.5 and now Xone works great on my machine..

Only problem now is, I can't get brawlhalla to recognize my controller. Other Steam games are working great however.

**Comment by guilhermearaujo** [comment]
The instructions don't say that. It doesn't even have a preferences icon.

**Comment by CSharkey145** [comment]
http://www.tekrevue.com/tip/xbox-one-controller-mac/

**Comment by CSharkey145** [comment]
I was following instructions from there, and it worked, just like that, after I got the new osx.

**Comment by CSharkey145** [comment]
Sorry, after looking into this more, I've realized I was mixing the two programs up. Apologies.
