### ISSUE TITLE
Doesn't work on OSX 10.10

### ISSUE THREAD

**Issue by dennis-van-bennekom** [guilhermearaujo/xboxonecontrollerenabler#3]
I tried using this on OSX 10.10. It looks like it works. It sees my input on the buttons etc. But when I try to use it in a game that worked with the controller on OSX 10.9 it doesn't recognize my controller.

I also tried to build from source and I got the same issue.

**Comment by guilhermearaujo** [comment]
After further testing, I noticed that indeed `kext-dev-mode` should be enabled for better compatibility. Instructions will be added to the readme.
